export enum Tools {
    RectOpen = "rect-open",
    RectClosed = "rect-closed",
    RoundRectOpen = "round-rect-open",
    RoundRectClosed = "round-rect-closed",
    CircleOpen = "circle-open",
    CircleClosed = "circle-closed",
    TriangleOpen = "tri-open",
    TriangleClosed = "tri-closed",
    Line = "line",
    Cursor = "cursor",
    PaintBrush = "paint-brush",
    PaintBucket = "paint-bucket",
    Text = "text",
    Image = "image",
    HeartClosed = "heart-closed",
    StarOpen = "star-open",
}